/*
 * Code to controll an 8x8x8 ledcube using avr
 * http://www.instructables.com/id/Led-Cube-8x8x8/
 * See lisence.txt for lisence.
 */
#include "main.h"
#include "effect.h"
#include "launch_effect.h"
#include "draw.h"

// Main loop
// the AVR enters this function at boot time
int main (void)
{

	// This function initiates IO ports, timers, interrupts and
	// serial communications
	ioinit();

	// This variable specifies which layer is currently being drawn by the
	// cube interrupt routine. We assign a value to it to make sure it's not >7.
	current_layer = 1;

	int i;

	// Light the green LED
	LED_PORT |= LED_GREEN;

	// Set a seed for the random number generator
	srand(1337);

	// Enable interrupts
	// This starts the routine that draws the cube content
	sei();

	// Go into rs232 mode if the rs232 switch is enabled.
	if (!(PIND & RS232_BTN)) {
		rs232();
	}

	// Do awesome effects. Loop forever.
	while (1)
	{
		effect_path_bitmap(1500, 2, 2);
		effect_path_text(1800, "FH Aachen");
		launch_effect(rand() % EFFECTS_TOTAL);
		effect_path_text(1800, "BMT");
		launch_effect(rand() % EFFECTS_TOTAL);
		effect_stringfly2("FH AACHEN");
		launch_effect(rand() % EFFECTS_TOTAL);
	}
}

/*
 * Multiplexer/framebuffer routine
 * This function is called by an interrupt generated by timer 2.
 * Every time it runs, it does the following:
 * 1) Disable the output for the multiplexer array.
 * 2) Turn of all layers.
 * 3) Load the current layer from the cube buffer onto the
 *    multiplexer array.
 * 4) Enable output from the multiplexer array.
 * 5) Turn on the current layer.
 * 6) Increment the current_layer variable, so the next layer is
 *    drawn the next time this function runs.
*/

ISR(TIMER2_COMP_vect)
{
	int i;

	LAYER_SELECT = 0x00; // Turn all cathode layers off. (all transistors off)
	OE_PORT |= OE_MASK; // Set OE high, disabling all outputs on latch array

	// Loop through all 8 bytes of data in the current layer
	// and latch it onto the cube.
	for (i = 0; i < 8; i++)
	{
		// Set the data on the data-bus of the latch array.
		PORTA = cube[current_layer][i];
		// Increment the latch address chip, 74HC138, to create
		// a rising edge (LOW to HIGH) on the current latch.
		LATCH_ADDR = (LATCH_ADDR & LATCH_MASK_INV) | (LATCH_MASK & (i+1));
	}

	OE_PORT &= ~OE_MASK; // Set OE low, enabling outputs on the latch array
	LAYER_SELECT = (0x01 << current_layer); // Transistor ON for current layer

	// Increment the curren_layer counter so that the next layer is
	// drawn the next time this function runs.
	current_layer++;
	// We want to count from 0-7, so set it to 0 when it reaches 8.
	if (current_layer == 8)
		current_layer = 0;
}


void ioinit (void)
{
	DDRA = 0xff;	// DATA bus output
	DDRB = 0xef;	// Button on B4
	DDRC = 0xff;	// Layer select output
	DDRD = 0xdf;	// Button on D5


	PORTA = 0x00; // Set data bus off
	PORTC = 0x00; // Set layer select off
	PORTB = 0x10; // Enable pull up on button.
	PORTD = 0x20; // Enable pull up on button.


	// Timer 2
	// Frame buffer interrupt
	// 14745600/128/11 = 10472.72 interrupts per second
	// 10472.72/8 = 1309 frames per second
	OCR2 = 10; 	// interrupt at counter = 10
	TCCR2 |= (1 << CS20) | (1 << CS22); // Prescaler = 128.
	TCCR2 |= (1 << WGM21); // CTC mode. Reset counter when OCR2 is reached.
	TCNT2 = 0x00;	// initial counter value = 0;
	TIMSK |= (1 << OCIE2); // Enable CTC interrupt



	// Initiate RS232
	// USART Baud rate is defined in MYUBRR
	UBRRH = MYUBRR >> 8;
	UBRRL = MYUBRR;
	// UCSRC - USART control register
	// bit 7-6      sync/ascyn 00 = async,  01 = sync
	// bit 5-4      parity 00 = disabled
	// bit 3        stop bits 0 = 1 bit  1 = 2 bits
	// bit 2-1      frame length 11 = 8
	// bit 0        clock polarity = 0
	UCSRC  = 0b10000110;
	// Enable RS232, tx and rx
	UCSRB = (1<<RXEN)|(1<<TXEN);
	UDR = 0x00; // send an empty byte to indicate powerup.
}

// Take input from a computer and load it onto the cube buffer
void rs232(void)
{
	int tempval;
	int x = 0;
	int y = 0;
	int escape = 0;

	while (1)
	{
		// Switch state on red LED for debugging
		// Should switch state every time the code
		// is waiting for a byte to be received.
		LED_PORT ^= LED_RED;

		// Wait until a byte has been received
		while ( !(UCSRA & (1<<RXC)) );

		// Load the received byte from rs232 into a buffer.
		tempval = UDR;

		// Uncommet this to echo data back to the computer
		// for debugging purposes.
		//UDR = tempval;

		// Every time the cube receives a 0xff byte,
		// it goes into sync escape mode.
		// if a 0x00 byte is then received, the x and y counters
		// are reset to 0. This way the x and y counters are
		// always the same on the computer and in the cube.
		// To send an 0xff byte, you have to send it twice!

		// Go into sync escape mode
		if (tempval == 0xff)
		{
			// Wait for the next byte
			 while ( !(UCSRA & (1<<RXC)) );
			 // Get the next byte
			 tempval = UDR;

			 // Sync signal is received.
			 // Reset x and y counters to 0.
			 if (tempval == 0x00)
			 {
				x = 0;
				y = 0;
				escape = 1;
			 }
			 // if no 0x00 byte is received, proceed with
			 // the byte we just received.
		}

		if (escape == 0)
		{
		// Load data into the current position in the buffer
		fb[x][y] = tempval;

			// Check if we have reached the limits of the buffer array.
			if (y == 7)
			{
				if (x == 7)
				{
					// All data is loaded. Reset both counters
					y = 0;
					x = 0;
					// Copy the data onto the cube.
					tmp2cube();
				} else
				{
					// A layer is loaded, reset y and increment x.
					x++;
					y = 0;
				}
			} else
			{
				// We are in the middle of loading a layer. increment y.
				y++;
			}
		} else {
			escape = 0;
		}
	}
}
